name=input("Enter your name:")
plot=int(input("Enter your plot number:"))
Po=input("Enter your Post Office:")
City=input("Enter your city:")
Pin=int(input("Enter your pincode:"))
print("Name:", name)
print("At/Plot:", plot)
print("Po:", Po)
print("City:", City)
print("Pincode:", Pin)